version: '3.8'
services:
  payoorserver:
    container_name: payoorserver
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/data/certs:/etc/nginx/certs
      

  payoordb:
    container_name: payoordb
    image: mongo
    environment:
      - PORT=27017
    volumes:
      - /data-vol:/data/payoordb

  payoorchat:
    container_name: payoorchat
    restart: always
    build: ./chat
    environment:
      - PORT=8080

  payoorwl:
    container_name: payoorwl
    restart: always
    build: ./waitlist
    environment:
      - PORT=8081
