version: '3.8'
services:
  payoorserver:
    container_name: payoorserver
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/data/certs:/etc/nginx/certs
    depends_on:
      - payoorapi

  payoordb:
    container_name: payoordb
    image: mongo
    environment:
      - PORT=27017
    volumes:
      - /data-vol:/data/payoordb

  payoorapi:
    container_name: payoorchat
    restart: always
    build: ./server
    environment:
      - PORT=8080
